# Generated by Django 3.2.6 on 2021-09-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='car_id',
            new_name='cart_id',
        ),
    ]
